#include <stdio.h>
#include "combined.h"

int main() {

    int choice=-1;
    //Stores the choice entered by the user to process the further switch case. User can enter any of the options mentioned ahead
    int filled=0;
    //Variable to keep the track of the number of rows filled in the main "Energy_Trans" array of the main structure
    int month;
    //Stores the month in which maximum transactions take place
    int lstsellerfilled=0, lstbuyerfilled=0;
    //Variables to keep the track of number of rows filled in the list of sellers and buyers respectively
    int max_trans_index;
    //Stores the index of maximum amount of energy traded in the list of all transactions

    struct SmartGridTransaction Energy_Trans[SIZE];
    //Array of the main structure which contains the attribures such as Transaction ID, Buyer ID, Seller ID, and so on
    struct seller_buyer ListTransSeller[SIZE];
    //List of each seller. It contains all the transactions of every seller
    struct seller_buyer ListTransBuyer[SIZE];
    //List of each buyer. It contains all the transactions of every buyer

    float revenueGen[SIZE];
    //Stores the total revenue generated by every seller
    float energyBought[SIZE];
    //Stores the total amount of energy bought by each buyer

    
    hardcode(Energy_Trans);
    //Function to initially enter 25 values in the structure
    filled=25;
    //Update filled to 25 after entering the initial values


    printf("Greetings to the user!\nHere are a bunch of operations.\nWhich one do you like to do?\n\n");
    while(choice != 0) {    

        printf("1. To add new entries enter 1\n");
        printf("2. To display the values enter 2\n");
        printf("3. To create a list for every seller enter 3\n");
        printf("4. To create a list for every buyer enter 4\n");
        printf("5. To get the number of transactions in a given time period enter 5\n");
        printf("6. To find the month in which maximum transactions took place enter 6\n"); 
        printf("7. To calculate the total revenue generated by a seller enter 7\n");     
        printf("8. To sort the list of sellers based on the revenue generated enter 8\n");
        printf("9. To find the transaction with the highest amount of energy transaction enter 9\n");
        printf("10. To sort the list of buyers based on the energy bought enter 10\n");
        printf("11. To find out a pair of buyer and seller involved in the maximum transaction enter 11\n");
        printf("12. To sort all buyer-seller pairs in the decreasing order of the number of transactions between them enter 12\n");
        printf("13. To sort all buyer-seller pairs in the decreasing order of the revenue exchanged between them enter 13\n");
        printf("14. To exit the application enter 0\n\n");

        scanf("%d",&choice);

        switch(choice) {

            case 1:
                filled=inputValues(Energy_Trans, filled,SIZE);
            break;

            case 2:                
                displayData(Energy_Trans,filled);
            break;

            case 3:
                lstsellerfilled=createListSeller(Energy_Trans,filled,ListTransSeller,lstsellerfilled);
            break;

            case 4:
                lstbuyerfilled=createListBuyer(Energy_Trans,filled,ListTransBuyer,lstbuyerfilled);
            break;

            case 5:
                list(Energy_Trans,filled);
            break;

            case 6:                
                month=maxMonth(Energy_Trans,filled);
                char monthName[12][10]={"January","February","March","April","May","June","July","August","September","October","November","December"};
                printf("The month in which maximum transactions occur is %s\n\n", monthName[month-1]);                
            break;

            case 7:
                if(lstsellerfilled==0) printf("The list of sellers has not been created.");
                else totalRevenue(ListTransSeller,revenueGen,lstsellerfilled);
            break;

            case 8:
                if(revenueGen[0]==0) {
                    if(lstsellerfilled!=0) printf("Please create the list of revenues for sellers using '7'\n");
                    else printf("Please create the list of sellers using '3' and then create the list of revenues using '7'"); 
                }
                else sortSellerList(ListTransSeller,lstsellerfilled,revenueGen);
            break;

            case 9:               
                max_trans_index=maxTradingTrans(Energy_Trans,filled);
                printf("The maximum energy transaction occured at:\n");
                printf("Transaction ID: %d\n",Energy_Trans[max_trans_index].transactionID);
                printf("Amount of energy traded: %f KWh\n",Energy_Trans[max_trans_index].amountOfEnergy);
                printf("Date: %s\n",Energy_Trans[max_trans_index].date);
                printf("Seller: %d\tBuyer: %d\n\n",Energy_Trans[max_trans_index].sellerID,Energy_Trans[max_trans_index].buyerID);                
            break;

            case 10:
                if(lstbuyerfilled==0) printf("The list of buyers is empty. Please create it using '4'\n");
                else sortBuyerList(ListTransBuyer,energyBought,lstbuyerfilled);
            break;

            case 11:
                pairWithMaxTrans(Energy_Trans,filled);
            break;

            case 12:
                sort_trans(Energy_Trans, filled);
            break;

            case 13:
                sort_rev(Energy_Trans, filled);
            break;

            default:
                choice = 0;
        }
    }
} 